# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/merli/ECE385Final/ECE385Final/ECE385Final.srcs/sources_1/ip/vaporwave_rom/vaporwave_rom.xci
# IP: The module: 'vaporwave_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/merli/ECE385Final/ECE385Final/ECE385Final.gen/sources_1/ip/vaporwave_rom/vaporwave_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vaporwave_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/merli/ECE385Final/ECE385Final/ECE385Final.srcs/sources_1/ip/vaporwave_rom/vaporwave_rom.xci
# IP: The module: 'vaporwave_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/merli/ECE385Final/ECE385Final/ECE385Final.gen/sources_1/ip/vaporwave_rom/vaporwave_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vaporwave_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
